// VRChat Wrap — Cloudflare Worker
// Handles two things:
//   1. World thumbnail proxy (original) — GET /?id=wrld_xxx
//   2. Leaderboard via D1             — GET|POST /lb/*
//
// Required setup:
//   npx wrangler d1 create vrcwrap-lb
//   npx wrangler d1 execute vrcwrap-lb --file=schema.sql
//   npx wrangler secret put SUBMIT_SECRET   ← plain key, same value obfuscated in index.html
//   npx wrangler deploy worker.js
//
// wrangler.toml must have:
//   [[d1_databases]]
//   binding = "DB"
//   database_name = "vrcwrap-lb"
//   database_id = "YOUR_D1_ID"

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Cache-Control': 'no-cache',
};

// Whitelist of columns allowed in ORDER BY / WHERE — prevents SQL injection
const VALID_COLS = new Set([
  'hours','worlds','people_met','friends_added',
  'solo_pct','one_time_people','unfriended','empty_hours',
]);

// Max allowed values per field — server-side sanity check
const FIELD_MAX = {
  hours: 50000, worlds: 30000, people_met: 500000,
  friends_added: 10000, solo_pct: 100,
  one_time_people: 200000, unfriended: 5000, empty_hours: 50000,
};

export default {
  async fetch(req, env) {
    if (req.method === 'OPTIONS') return new Response(null, { headers: CORS });

    const url  = new URL(req.url);
    const path = url.pathname.replace(/\/+$/, '') || '/';

    // ── /lb/count — total submissions ─────────────────────────────
    if (path === '/lb/count' && req.method === 'GET') {
      const row = await env.DB.prepare('SELECT COUNT(*) as n FROM leaderboard').first();
      return json({ count: row?.n ?? 0 });
    }

    // ── /lb/top — top 100 for a category ──────────────────────────
    if (path === '/lb/top' && req.method === 'GET') {
      const col = url.searchParams.get('col') || '';
      if (!VALID_COLS.has(col)) return json({ error: 'invalid col' }, 400);
      const { results } = await env.DB.prepare(
        `SELECT username, role_code, role_name, ${col}
         FROM leaderboard ORDER BY ${col} DESC LIMIT 100`
      ).all();
      return json({ data: results });
    }

    // ── /lb/rank — rank of a specific value ───────────────────────
    if (path === '/lb/rank' && req.method === 'GET') {
      const col = url.searchParams.get('col') || '';
      const val = parseFloat(url.searchParams.get('val') || '');
      if (!VALID_COLS.has(col) || isNaN(val)) return json({ error: 'invalid params' }, 400);
      const row = await env.DB.prepare(
        `SELECT COUNT(*) as n FROM leaderboard WHERE ${col} > ?`
      ).bind(val).first();
      return json({ rank: (row?.n ?? 0) + 1 });
    }

    // ── /lb/submit — upsert a score ───────────────────────────────
    if (path === '/lb/submit' && req.method === 'POST') {
      let body;
      try { body = await req.json(); }
      catch { return json({ error: 'invalid json' }, 400); }

      const { sig, ...data } = body;

      // Verify HMAC — rejects requests not generated by the app
      if (!env.SUBMIT_SECRET || !await verifyHMAC(data, sig, env.SUBMIT_SECRET))
        return json({ error: 'unauthorized' }, 403);

      // Validate username
      const uname = String(data.username ?? '').trim();
      if (uname.length < 2 || uname.length > 64)
        return json({ error: 'invalid username' }, 400);

      // Validate numeric fields
      for (const [field, max] of Object.entries(FIELD_MAX)) {
        const v = Number(data[field] ?? 0);
        if (isNaN(v) || v < 0 || v > max)
          return json({ error: `invalid ${field}` }, 400);
      }

      await env.DB.prepare(`
        INSERT INTO leaderboard
          (username, username_lower, hours, worlds, people_met, friends_added,
           solo_pct, one_time_people, unfriended, empty_hours,
           role_code, role_name, submitted_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'))
        ON CONFLICT(username_lower) DO UPDATE SET
          username=excluded.username, hours=excluded.hours,
          worlds=excluded.worlds, people_met=excluded.people_met,
          friends_added=excluded.friends_added, solo_pct=excluded.solo_pct,
          one_time_people=excluded.one_time_people, unfriended=excluded.unfriended,
          empty_hours=excluded.empty_hours, role_code=excluded.role_code,
          role_name=excluded.role_name, submitted_at=datetime('now')
      `).bind(
        uname, uname.toLowerCase(),
        Math.round(data.hours ?? 0),
        Math.round(data.worlds ?? 0),
        Math.round(data.people_met ?? 0),
        Math.round(data.friends_added ?? 0),
        Math.round(data.solo_pct ?? 0),
        Math.round(data.one_time_people ?? 0),
        Math.round(data.unfriended ?? 0),
        Math.round((data.empty_hours ?? 0) * 10) / 10,
        String(data.role_code ?? '').slice(0, 10),
        String(data.role_name ?? '').slice(0, 60),
      ).run();

      return json({ success: true });
    }

    // ── World thumbnail proxy (original behaviour) ─────────────────
    const id = url.searchParams.get('id') || '';
    if (!/^wrld_[0-9a-fA-F-]{36}$/.test(id))
      return json({ error: 'invalid world id' }, 400);

    let r;
    try {
      r = await fetch('https://api.vrchat.cloud/api/1/worlds/' + id, {
        headers: { 'User-Agent': 'vrchat-wrap/1.0 (github.io static site)' },
        cf: { cacheTtl: 86400, cacheEverything: true },
      });
    } catch { return json({ error: 'fetch failed' }, 502); }
    if (!r.ok) return json({ error: 'upstream', status: r.status }, r.status);

    const w = await r.json();
    return json({
      name: w.name, authorName: w.authorName,
      thumbnailImageUrl: w.thumbnailImageUrl, imageUrl: w.imageUrl,
    });
  },
};

// Verify HMAC-SHA256 signature produced by the client
// Data is canonicalised (sorted keys) so both sides produce identical JSON
async function verifyHMAC(data, sig, secret) {
  if (!sig || !secret) return false;
  try {
    const key = await crypto.subtle.importKey(
      'raw', new TextEncoder().encode(secret),
      { name: 'HMAC', hash: 'SHA-256' }, false, ['verify']
    );
    const canonical = JSON.stringify(
      Object.keys(data).sort().reduce((o, k) => { o[k] = data[k]; return o; }, {})
    );
    const sigBytes = Uint8Array.from(atob(sig), c => c.charCodeAt(0));
    return await crypto.subtle.verify(
      'HMAC', key, sigBytes, new TextEncoder().encode(canonical)
    );
  } catch { return false; }
}

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  });
}
